apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesec_server
  name: kubesec_server
spec:
  ports:
  - name: https
    port: {{ .Values.kubesec_server.service.port }}
    protocol: TCP
    targetPort: {{ .Values.kubesec_server.deployument.containerPort }}
  selector:
    app: kubesec_server
  type: {{ .Values.kubesec_server.service.type }}
