apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhook-server
  name: webhook-server
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: webhook-server
  type: ClusterIP
