apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubesec_server
  name: kubesec_server
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: kubesec_server
  type: ClusterIP
